# A list of keywords from IMDB related potentially to award names.
AWARDS_KEYWORDS = [
    "movie",
    "series",
    "screenplay",
    "motion",
    "picture",
    "supporting",
    "actor",
    "actress",
    "director",
    "comedy",
    "musical",
    "drama",
    "foreign",
    "language",
    "mini-series",
    "mini",
    "series",
    "television",
    "tv",
    "score",
    "producer",
    "cinematography",
    "cinematagrapher",
    "song",
    "original",
    "role",
    "picture",
    "animated",
    "feature",
    "film",
    "horror",
    "writer",
    "star",
    "composer",
    "singer",
    "artist",
    "songwriter",
    "western",
    "cast",
    "soundtrack",
    "music",
    "languages",
    "action",
    "adventure",
    "biography",
    "sci-fi",
    "science",
    "fiction",
    "romance",
    "rom-com",
    "short",
    "romantic-comedy",
    "thriller",
    "war",
    "sport",
    "documentary",
    "mystery",
    "fantasy",
    "film-noir",
    "game-show",
    "talk-show",
    "sit-com",
    "satire",
    "news",
    "game",
    "talk",
    "situational",
    "reality",
    "family",
    "children",
]

TRASH_KEYWORDS = [
        " goes ",
        " is ",
        " http",
        " https",
        " for ",
        " at ",
        " because ",
        " but ",
        " he ",
        " she ",
        " they ",
        " after ",
        " before ",
        " winner ",
        " despite ",
        " sex ",
        " gives ",
        " goes ",
        " wins ",
        " golden ",
        " globes ",
        " yet ",
        " close ",
        " due "
        " and ",
        " over ",
        " while ",
        " who ",
    ]

MINOR_KEYWORDS = [
        " in ",
        " on ",
        " for ",
        " a ",
        " by ",
        " an ",
        " or ",
        " and ",
        " the ",
        " nor ",
        " yet ",
        " but ",
        " so ",
        " to ",
        " from ",
        " of ",
        " under ",
        " over ",
        " at ",
        " within ",
        " between ",
        " through ",
    ]

PERSON_KEYWORDS = [
    "actor",
    "actress",
    "director",
    "writer",
    "producer"
]
